/****************************************************************************
 *
 * gen-dna.c - Generate input for omp-c-ray
 *
 * Copyright (C) 2022, 2023 Moreno Marzolla
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/

/***
% Generate input for omp-c-ray
% [Moreno Marzolla](https://www.unibo.it/sitoweb/moreno.marzolla)
% Last updated: 2023-11-03

Inspired by <https://twitter.com/pickover/status/1505350972641525765>

Compile with:

        gcc -std=c99 -Wall -Wpedantic gen-dna.c -o gen-dna

Run with:

        ./gen-dna | ./omp-c-ray -o dna.pbm

Better looking, but much slower:

        ./gen-dna | ./omp-c-ray -s 1024x768 -r 10 -o dna.pbm

***/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

enum {RED, BLUE};

/**
 * A sphere of radius sz and center (cx, cy, cz)
 */
void sphere( float sz, float cx, float cy, float cz, int color )
{
    printf("s  %f %f %f  %f  %s  50 0.2\n",
           cx, cy, cz, sz, color == BLUE ? "0 0 0.2" : "0.2 0 0");
}

int main( int argc, char *argv[] )
{
    int n = 30;

    if (argc > 2) {
        fprintf(stderr, "Usage %s [n_spheres]\n", argv[0]);
        return EXIT_FAILURE;
    }

    if (argc > 1) {
        n = atoi(argv[1]);
    }

    printf("# Input for omp-c-ray\n");
    printf("# Generated by %s %d\n", argv[0], n);
    const double r = 2.0;
    const double deltay = 0.25;
    const double deltaa = 0.4;
    double alpha = 0.0;
    double y = 0;
    for (int i=0; i<n; i++) {
        const double x = r * sin(alpha);
        const double z = r * cos(alpha);
        sphere(0.5, x, y, z, RED);
        sphere(0.5, -x, y, -z, BLUE);
        y += deltay;
        alpha += deltaa;
    }
    printf("s 10010 0 0   10000   0.3 0.5 0.3     8.0   0.1\n");  // left wall
    printf("s 0 0 10010   10000   0.5 0.3 0.3    40.0   0.1\n");  // right wall
    printf("s 0 -10003 0  10000   0.2 0.35 0.5   80.0   0.05\n"); // floor
    printf("l -50 50 -20\n"); // lights
    printf("l -20 100 -50\n");
    printf("c  -10 5 -15   90  0 2 0\n"); // camera

    return EXIT_SUCCESS;
}
