/****************************************************************************
 *
 * gen-graph.c -- Generate random graphs in DIMACS format.
 *
 * Copyright (C) 2025 Moreno Marzolla
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

int main( int argc, char *argv[] )
{
    int n = 100, m = 0;
    double rho = 0.5;
    int *d;

    if (argc > 4) {
        fprintf(stderr, "Usage: %s [n [rho]]]\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    if (argc > 1) {
        n = atoi(argv[1]);
        assert(n > 0);
    }
    if (argc > 2) {
        rho = atof(argv[2]);
        assert((rho >= 0.0) && (rho <= 1.0));
    }

    d = (int*)malloc(n*n*sizeof(*d)); assert(d != NULL);
    for (int u=0; u<n; u++) {
        for (int v=0; v<n; v++) {
            d[u*n+v] = -1;
        }
    }

    for (int u=0; u<n; u++) {
        for (int v=0; v<n; v++) {
            if ( (rand()/(double)RAND_MAX < rho) && (u != v) ) {
                d[u*n + v] = 1 + rand() % 100;
                m++;
            }
        }
    }

    printf("c generated by gen-graph, n=%d m=%d\n", n, m);
    printf("p sp %d %d\n", n, m);
    for (int u=0; u<n; u++) {
        for (int v=0; v<n; v++) {
            if (d[u*n+v] >= 0) {
                /* Nodes of graphs in DIMACS format are numbered
                   starting from 1, not zero, so we need to adjust for
                   that. */
                printf("a %d %d %d\n", u+1, v+1, d[u*n+v]);
            }
        }
    }
    free(d);
    return EXIT_SUCCESS;
}
