/****************************************************************************
 *
 * gen-spheres.c - Generate input for omp-c-ray
 *
 * Copyright (C) 2022, 2023 Moreno Marzolla
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/

/***
% Generate input for omp-c-ray
% [Moreno Marzolla](https://www.unibo.it/sitoweb/moreno.marzolla)
% Last updated: 2023-11-03

Inspired by <https://twitter.com/pickover/status/1505350972641525765>.

Compile with:

        gcc -std=c99 -Wall -Wpedantic gen-spheres.c -o gen-spheres

Run with:

        ./gen-spheres | ./omp-c-ray -o spheres.pbm

***/

#include <stdio.h>
#include <stdlib.h>

/**
 * A sphere of radius sz and center (cx, cy, cz)
 */
void sphere( float sz, float cx, float cy, float cz )
{
    printf("s  %f %f %f  %f  0.0 0.0 0.2  40 0.9\n",
           cx, cy, cz, sz);
}

int main( int argc, char *argv[] )
{
    int size = 10;

    if (argc > 2) {
        fprintf(stderr, "Usage %s [size]\n", argv[0]);
        return EXIT_FAILURE;
    }

    if (argc > 1) {
        size = atoi(argv[1]);
    }

    printf("# Input for omp-c-ray\n");
    printf("# Generated by %s %d\n", argv[0], size);
    for (int i=0; i<size; i++) {
        for (int j=0; j<size; j++) {
            sphere(0.5, i, 0.8, j);
            sphere(0.5, i, -0.8, j);
        }
    }
    printf("s  0   -10050 0    10000    0.2 0.35 0.5    80.0    0.4\n"); /* floor   */
    printf("l -50 100 -50\n"); /* lights */
    printf("l 10 0 0\n");
    printf("c  -1.5 0 -1.5   170  0 0 0\n"); /* camera */

    return EXIT_SUCCESS;
}
